### PR TITLE
Create output folder if it doesn't exist

### PR DESCRIPTION
**Pull request by spyrkob**

### CODE REVIEW

**Comment by TomasHofman** [comment]
Thanks @spyrkob , I thought it gets created automatically, but maybe only in some circumstances. Do you want me to release now?

**Comment by spyrkob** [comment]
The problematic scenario is when you use the plugin with a project that doesn't usually create 'target' - e.g. `<type>pom</type>`. Sorry should have added that to the description.

I don't need a release straight away, just something I came across at one point :)

**Comment by TomasHofman** [comment]
Great, thanks!

**Comment by TomasHofman** [comment]
This was released in https://github.com/wildfly-extras/wildfly-channel-maven-plugin/releases/tag/1.0.12

**Pull request merged**
