### PR TITLE
[SET-677] Generate manifest based on projects dependencies

### PR DESCRIPTION
**Pull request by spyrkob**
Issue: https://issues.redhat.com/browse/SET-677

### CODE REVIEW

**Comment by spyrkob** [comment]
@TomasHofman could you review this when you have a moment please?

**Comment by TomasHofman** [comment]
Thanks @spyrkob , I will try to review tomorrow.

**Review by TomasHofman — APPROVED** [review]
It looks fine to me.

I'm only thinking about a change in how the manifest is produced - instead of printing on stdout or generating file specified by system property, should the manifest rather be generated as standard build artifact?

It could look like having `target/manifest.yaml` file generated in the execution root module, and if user calls `deploy` or `install` goals that file would be automatically installed to relevant maven repo.

That would allow to configure the plugin to be part of standard project build, with the artifact being generated at every build and published under project GAV.

**Comment by TomasHofman** [comment]
The plugin could then replace most of the stuff that Brian did there: https://gitlab.cee.redhat.com/jboss-eap/eap-product-conf/-/merge_requests/1/diffs

**Comment by TomasHofman** [comment]
I will push a commit I was experimenting with and you will see if you want to change it differently.

**Comment by TomasHofman** [comment]
https://github.com/TomasHofman/wildfly-channel-maven-plugin/commit/cec5daf04d2bdedd6201bb9fcce02418fec651e5

**Comment by TomasHofman** [comment]
In a test project I used something like this:

```
            <plugin>
                <groupId>org.wildfly</groupId>
                <artifactId>wildfly-channel-maven-plugin</artifactId>
                <version>1.0.4-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>create-manifest</goal>
                        </goals>
                        <configuration>
                            <manifestId>mjolnir-manifest</manifestId>
                            <manifestName>Mjolnir Archive Service Manifest</manifestName>
                            <manifestDescription>Description...</manifestDescription>
                        </configuration>
<!--                        <inherited>false</inherited>-->
                    </execution>
                </executions>
            </plugin>
```

**Comment by spyrkob** [comment]
thanks @TomasHofman, I added your commit. I changed the name of the generated file to match other artifacts (so it's `target/${artifactId}-${version}-manifest.yaml`

**Comment by TomasHofman** [comment]
Was released as 1.0.5.

**Pull request merged**
